### PR TITLE
Fix confusing sort by time implementation #147

### PR DESCRIPTION
**Pull request by simontb**
This fixes the confusing sort by time implementation that I mentioned in issue #147 

I also had to adjust the unit tests in `ThePassSorting`, because they were designed for the wrong sorting by the comparator that did not bother the app, because of the mixed keys.

### CODE REVIEW

**Comment by ligi** [comment]
Thanks! But the issue I see that this would silently change the sort-order for current users

**Comment by simontb** [comment]
I had this concern as well, but since I changed `PassSortOrder` and `PassByTimeComparator`, current users won't notice a change. I also verified on my device by installing the old version first, sort the passes, and then install with my changes. Please test yourself and let me know in case you run into any issues.

**Comment by ligi** [comment]
Ah looks you are right. Will just do some more tests and let the CI run over the changes. Thanks! :+1: can you please add yourself to the credits?

**Comment by simontb** [comment]
Done

**Comment by ligi** [comment]
Thanks so much!

**Pull request merged**
