### PR TITLE
added swipe functionality

### LINKED ISSUE #29: Go to the next/previous pass when viewing one
It would be great if you could go to the next/previous pass with a swipe gesture, like in the Gmail app.

### LINKED ISSUE #211: Enhancement: Swipe to switch between passes
If I travel with my family I have all their passes in PassAndroid. During boarding, baggage drop, etc it always takes quite some time because I have to open one pass, go back, open the next pass and so on. It would be really nice and speed up the whole process if I could swipe to the right/left to go to the previous/next pass.  

At the moment I often take screenshots in advance from the PassAndroid screens as a work around, because then I can swipe through the passes quickly with the gallery app.

### PR DESCRIPTION
**Pull request by irgendwr**
This pullrequest adds support for swiping between passes by adding a ViewPager.

Fixes #211, Fixes #29 and might be an alternative to #91

### CODE REVIEW

**Comment by ligi** [comment]
Thanks! Looks great on the first glance - will have a deeper look and most likely merge after work today

**Comment by irgendwr** [comment]
*bump*, in case you forgot ^^
By the way: What does the spoon stage stand for?

**Comment by ligi** [comment]
I am so sorry for the delay - but the timing was really bad as this week is Berlin blockhain week and this is jam packed currently coding at ETHBerlin hackathon - can only really deeply look at it next tuesday - very sorry for this. Spoon is this: https://github.com/square/spoon
Thanks again for the PR - will not be forgotten - but cannot do it now - hope you understand

**Comment by irgendwr** [comment]
No problem, have fun! 😄

**Comment by ligi** [comment]
Thanks for the PR & sorry for the late merge! Also feel free to make a PR so you get into the credits as this is a substantial contribution

**Comment by simontb** [comment]
@ligi can you make the current version available on Google Play as well? or what's the schedule for the next release?

**Pull request merged**
