### PR TITLE
Pkpass renderer

### PR DESCRIPTION
**Pull request by jejb**
Thanks for the great program.  I've been having trouble with a few gate agents who don't like the look of the espass linear boarding pass.  To fix this, I've added a renderer to PassAndroid that looks much more like the apple PKPASS view.  In order to do this, I've had to add hints to the espass main.json about which region in the PKPASS the field belongs.  This is a screenshot of what the new layout looks like:

image

Which looks much closer to the apple specification for a boarding pass:

https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW8

### CODE REVIEW

**Comment by andrewshadura** [comment]
This is a great idea, @ligi could you please have a look at this as well if you find time? Thanks!

**Comment by ligi** [comment]
Yep - already looking - just need to test on some form-factors - this one is a bit more complicated than yours ;-)

**Comment by faizpuru** [comment]
Any news on that PR?

**Comment by ligi** [comment]
Thanks for the contribution and sorry for the late merge

**Pull request merged**
