### PR TITLE
Internationalization

### PR DESCRIPTION
**Pull request by scento**
This pull request includes a wide range of changes, which should improve the ability to translate the app for a greater range of locales:

* Replaces hardcoded English strings with resource references
* Use placeholders (`String.format`) instead of concanating strings manually
* Unifies the naming schema for string resources
* Adds all string resources in English and German

### CODE REVIEW

**Comment by ligi** [comment]
Thanks! This looks good - are you able to rebase this - then I will merge

**Comment by ligi** [comment]
I am also willing to rebase if the PRs are small - but this one is to big for me to rebase. Please resubmit as smaller PRs - also do not do language changes for a language which is not english in transifex not github. I can make you the coordinator for the german language there. So unfortunately I have to close this PR - but hope you submit parts of your changes in smaller PRs

**Comment by scento** [comment]
I will resubmit smaller PRs as soon as I get the time to do it.

**Comment by ligi** [comment]
thanks! :+1

On 13.03.2016 12:50, Wenzel Pünter wrote:
> I will resubmit smaller PRs as soon as I get the time to do it.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ligi/PassAndroid/pull/58#issuecomment-195940663>.
> 

-- 
friendly greetings,
ligi
http://ligi.de

**Comment by ligi** [comment]
One thing I forgot: please do not invest time in renaming string-ids - the pain is higher than the gain as this then has to be synced with transifex - I would rather avoid that

**Pull request closed without merging**
