### PR TITLE
feat: Add more barcode scanners

### PR DESCRIPTION
**Pull request by SimonIT**
Adds support for the beautiful [QR & Barcode Scanner](https://github.com/wewewe718/QrAndBarcodeScanner) app

### CODE REVIEW

**Comment by SimonIT** [comment]
Hey @ligi, it seems the CI doesn't work anymore?

**Comment by SimonIT** [comment]
Hey @ligi, are you still there?

**Comment by ligi** [comment]
sorry for the delay - weird times currently - reactivated the CI - but seems I need to care for the build env - somehow it currently searches semver only on jitpack - but not on mavenCentral

**Comment by SimonIT** [comment]
What's the lint error?
If I click on details I get an error 500.
I als tried it locally, but there it stops with a `GC overhead limit exceeded` or `Expiring Daemon because JVM heap space is exhausted`

**Pull request merged**
